"""Optional LLM refinement for deterministic clarification questions."""

from __future__ import annotations

import json

from threatmodel_ai.llm.client import LLMClient
from threatmodel_ai.model.schema import Edge, Evidence, Node, SystemModel
from threatmodel_ai.questions.generator import Question

_INSTRUCTIONS = """\
You refine security clarification questions for a threat model review.

Hard rules:
- system_model.json and deterministic questions are the only source of truth.
- Do not invent architecture, components, data stores, trust boundaries, controls, or threats.
- Do not answer the questions.
- Do not remove uncertainty. Unknown information must remain unknown.
- Preserve every deterministic question ID exactly.
- If evidence is weak or missing, say that the reviewer should confirm it.
- Return Markdown only.
"""


def refine_questions(
    *,
    model: SystemModel,
    questions: list[Question],
    client: LLMClient,
) -> str:
    """Refine deterministic questions into a separate non-authoritative Markdown artifact."""

    payload = {
        "system": _model_summary(model),
        "questions": [_question_summary(question) for question in questions],
    }
    refined = client.generate_text(
        instructions=_INSTRUCTIONS,
        input_text=json.dumps(payload, indent=2, sort_keys=True),
    ).strip()
    return _with_header(refined)


def _model_summary(model: SystemModel) -> dict[str, object]:
    nodes = [_node_summary(node) for node in model.nodes]
    edges = [_edge_summary(edge) for edge in model.edges]
    return {
        "name": model.name,
        "nodes": nodes,
        "edges": edges,
        "unknown_count": len(model.unknowns),
    }


def _node_summary(node: Node) -> dict[str, object]:
    return {
        "id": node.id,
        "name": node.name,
        "type": node.type.value,
        "trust_boundary_id": node.trust_boundary_id,
        "evidence": [_evidence_summary(item) for item in node.evidence[:3]],
    }


def _edge_summary(edge: Edge) -> dict[str, object]:
    return {
        "id": edge.id,
        "source": edge.source,
        "target": edge.target,
        "type": edge.type.value,
        "protocol": edge.protocol,
        "authentication": edge.authentication,
        "authorization": edge.authorization,
        "data_assets": edge.data_assets,
        "evidence": [_evidence_summary(item) for item in edge.evidence[:3]],
    }


def _question_summary(question: Question) -> dict[str, object]:
    return {
        "id": question.id,
        "category": question.category,
        "question": question.question,
        "rationale": question.rationale,
        "related_elements": question.related_elements,
        "derived_from": question.derived_from,
        "evidence": [_evidence_summary(item) for item in question.evidence[:3]],
    }


def _evidence_summary(value: Evidence) -> dict[str, object]:
    return {
        "source_type": value.source_type.value,
        "source_path": value.source_path,
        "extractor": value.extractor,
        "detail": value.detail,
        "line": value.line,
    }


def _with_header(markdown: str) -> str:
    header = "\n".join(
        [
            "# Refined Questions",
            "",
            "Generated by an optional LLM from deterministic `questions.md` and a minimal "
            "`system_model.json` summary. This file is not the source of truth.",
            "",
        ]
    )
    return header + markdown + "\n"
